---
title: Beat
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'TBD.'

baseurl:
url:
twitter_username: voxmedia
github_username: voxmedia
markdown: kramdown
gems:
- jekyll-feed
- jekyll-autoprefixer
exclude:
- Gemfile
- Gemfile.lock
- clock
- 2014
- 2015
- 2016

